export const actions = {
  SET_CURRENT_FILE: "SET_CURRENT_FILE",
  SET_CURRENT_REPO: "SET_CURRENT_REPO",
  SET_REPOS_LIST: "SET_REPOS_LIST",
  SET_FILES_LIST: "SET_FILES_LIST",
  SET_COMMIT_MESSAGE: "SET_COMMIT_MESSAGE",
  SET_FILE_CONTENT: "SET_FILE_CONTENT",
  CLEAR_FILE: "CLEAR_FILE",
  CLEAR_REPOS: "CLEAR_REPOS",
};
